/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaz;

/**
 *
 * @author gpint
 */
public class Voto extends javax.swing.JFrame {

    /**
     * Creates new form Voto
     */
    public Voto() {
        initComponents();
        this.setTitle("Votar");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel37 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel37.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 153, 153));
        jLabel37.setText("Seleccione el botón \"Votar\" bajo la foto de su candidato de preferencia.");
        jLabel37.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 24)); // NOI18N
        jLabel1.setText("ELECCIONES 2022");

        jLabel2.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 18)); // NOI18N
        jLabel2.setText("PRESIDENCIA Y VECIPRESIDENCIA DE LA REPUBLICA");

        jPanel1.setLayout(null);

        jButton1.setText("Votar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 110, 70, 22);

        jLabel4.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel4.setText("xxxxxxx xxxxxxxx");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 130, 90, 16);

        jLabel5.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel5.setText("Segunda Vicepresidencia");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(120, 120, 110, 16);

        jLabel7.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 12)); // NOI18N
        jLabel7.setText("Partido");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 10, 40, 13);

        jLabel8.setText("xxxxxxx xxxxxxxx");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(120, 30, 100, 16);

        jLabel9.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel9.setText("Primera Vicepresidencia");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(120, 90, 110, 16);

        jLabel10.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel10.setText("xxxxxxx xxxxxxxx");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 100, 90, 16);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(30, 10, 0, 90);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(140, 50, 0, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jLabel41.setText("jLabel38");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(140, 50, 50, 32);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel1.add(jLabel44);
        jLabel44.setBounds(30, 30, 70, 70);

        jPanel2.setLayout(null);

        jButton2.setText("Votar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 110, 70, 22);

        jLabel11.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel11.setText("xxxxxxx xxxxxxxx");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(130, 130, 90, 16);

        jLabel12.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel12.setText("Segunda Vicepresidencia");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(120, 120, 110, 16);

        jLabel14.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 12)); // NOI18N
        jLabel14.setText("Partido");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(150, 10, 40, 13);

        jLabel15.setText("xxxxxxx xxxxxxxx");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(120, 30, 100, 16);

        jLabel16.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel16.setText("Primera Vicepresidencia");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(120, 90, 110, 16);

        jLabel17.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel17.setText("xxxxxxx xxxxxxxx");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(130, 100, 90, 16);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(30, 10, 0, 90);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jPanel2.add(jLabel36);
        jLabel36.setBounds(140, 50, 0, 40);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jLabel40.setText("jLabel38");
        jPanel2.add(jLabel40);
        jLabel40.setBounds(140, 50, 50, 32);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel2.add(jLabel43);
        jLabel43.setBounds(30, 30, 70, 70);

        jPanel3.setLayout(null);

        jButton3.setText("Votar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(30, 110, 70, 22);

        jLabel19.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel19.setText("xxxxxxx xxxxxxxx");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(130, 130, 90, 16);

        jLabel20.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel20.setText("Segunda Vicepresidencia");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(120, 120, 110, 16);

        jLabel22.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 12)); // NOI18N
        jLabel22.setText("Partido");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(150, 10, 40, 13);

        jLabel23.setText("xxxxxxx xxxxxxxx");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(120, 30, 100, 16);

        jLabel24.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel24.setText("Primera Vicepresidencia");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(120, 90, 110, 16);

        jLabel25.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel25.setText("xxxxxxx xxxxxxxx");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(130, 100, 90, 16);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel3.add(jLabel13);
        jLabel13.setBounds(30, 10, 0, 90);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jPanel3.add(jLabel35);
        jLabel35.setBounds(140, 50, 0, 40);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jLabel38.setText("jLabel38");
        jPanel3.add(jLabel38);
        jLabel38.setBounds(140, 50, 50, 32);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(30, 30, 70, 70);

        jPanel4.setLayout(null);

        jButton4.setText("Votar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(30, 110, 70, 22);

        jLabel27.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel27.setText("xxxxxxx xxxxxxxx");
        jPanel4.add(jLabel27);
        jLabel27.setBounds(130, 130, 90, 16);

        jLabel28.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel28.setText("Segunda Vicepresidencia");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(120, 120, 110, 16);

        jLabel30.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 12)); // NOI18N
        jLabel30.setText("Partido");
        jPanel4.add(jLabel30);
        jLabel30.setBounds(150, 10, 40, 13);

        jLabel31.setText("xxxxxxx xxxxxxxx");
        jPanel4.add(jLabel31);
        jLabel31.setBounds(120, 30, 100, 16);

        jLabel32.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 10)); // NOI18N
        jLabel32.setText("Primera Vicepresidencia");
        jPanel4.add(jLabel32);
        jLabel32.setBounds(120, 90, 110, 16);

        jLabel33.setFont(new java.awt.Font("Microsoft Yi Baiti", 0, 10)); // NOI18N
        jLabel33.setText("xxxxxxx xxxxxxxx");
        jPanel4.add(jLabel33);
        jLabel33.setBounds(130, 100, 90, 16);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jPanel4.add(jLabel34);
        jLabel34.setBounds(140, 50, 0, 40);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bandera.png"))); // NOI18N
        jLabel39.setText("jLabel38");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(143, 50, 50, 32);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N
        jPanel4.add(jLabel42);
        jLabel42.setBounds(30, 30, 70, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Escudo.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/TSE.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(141, 141, 141))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(8, 8, 8)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel37)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Voto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Voto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
